nremote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "air"
layout: splash
title: Learn More About NFTs
description: Nerdy Blockchain License Plate
url: "https://nftplate.info/"
has_toc: false
search_enabled: false
footer_content: "Open Blockchain for Asset Disposition Alliance (OBADA)"
plugins: ['jekyll-include-cache']
atom_feed:
  hide: true
